forum_publication:
    resource: "@ForumBundle/Resources/config/routing/publication.yml"
    prefix:   /publication

forum_reponse:
    resource: "@ForumBundle/Resources/config/routing/reponse.yml"
    prefix:   /reponse

forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }
